[package]
name    = "dispcli-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "dispcli_core"
path = "./dispcli_core.rs"

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
globset    = { workspace = true }

[lints]
workspace = true
